import React from "react";

const RoiAndRoas = () => {
  return (
    <div class="basic-section article-wrapper js-article-wrapper ">
      <div class="bootcamp-article-nav">
        <div class="bootcamp-article-nav-column prev-column">
          <a
            href="/case-interview-basics/case-cracking-toolbox/practice-your-basics/qualitative-and-quantitative-analysis"
            class="nav-link"
            title="Qualitative and Quantitative Analysis"
          >
            <i class="fas fa-chevron-left nav-icon"></i> Previous article
          </a>
        </div>
        <div class="bootcamp-article-nav-column next-column"></div>
      </div>
      <article class="basic-article article-content js-article-content">
        <h2>
          <strong>ROI and ROAS</strong>
        </h2>
        <p>
          Advertising in general, especially in search engine marketing (SEA)
          and paid social media (Paid Social), is a must to gain new leads and
          customers online.{" "}
          <strong>
            In this context, it is important to regularly check the advertising
            campaigns for their efficiency and to optimize them
          </strong>
          . For this purpose,{" "}
          <a href="/en/case-interview-basics/case-cracking-toolbox/practice-your-basics">
            two key figures
          </a>{" "}
          are particularly relevant in the field of performance marketing that
          are also relevant for ongoing consultants that can be part of a{" "}
          <a href="https://www.preplounge.com/en/articles/case-interview">
            case interview
          </a>
          .
        </p>
        <h2>
          <strong>ROI (Return on Investments)&nbsp;</strong>
        </h2>
        <p>
          <strong>
            The ROI value indicates how much profit an advertising campaign has
            generated in relation to the capital invested
          </strong>
          . This value therefore indicates the extent to which the campaign was
          profitable.&nbsp;
        </p>
        <p>
          <strong>The formula is:</strong>
        </p>
        <p>(profit/sales) x (sales/total capital) x 100.</p>
        <p>
          <strong>Example:</strong>
        </p>
        <p>
          A company places Google advertising for 10,000 euros and subsequently
          takes in 15,000 euros. The profit is therefore 5,000 euros. This
          results in the following ROI:
        </p>
        <ul>
          <li>10,000 euros total capital</li>
          <li>15.000 Euro turnover</li>
          <li>5.000 Euro profit</li>
        </ul>
        <p>
          <strong>(5,000/15,000) x (15,000/10,000) x 100 = 50</strong>
        </p>
        <p>
          The ROI can therefore be set at 50%. It depends on the industry which
          ROI value is considered profitable. In principle, the value should be
          at least 10, and is considered ideal from 15 to 25 percent.&nbsp;
        </p>
        <h2>
          <strong>ROAS (Return on advertising spend)&nbsp;</strong>
        </h2>
        <p>
          With ROAS, it is possible to calculate even more precisely what profit
          is achieved per advertisement.{" "}
          <strong>
            This makes it a subsection of ROI and an important indicator,
            especially in digital marketing and e-commerce
          </strong>
          . Since various bidding strategies are possible with Google Ads, for
          example, it is important to evaluate which strategy is most promising
          for which advertising campaign.&nbsp;
        </p>
        <p>
          <strong>The formula is:</strong>
        </p>
        <p>Revenue) / Advertising spend x 100</p>
        <p>
          <strong>Example:&nbsp;</strong>
        </p>
        <p>
          A company makes 100,000 euros in sales in an online store and the
          expenditure on advertising is 10,000 euros.
        </p>
        <ul>
          <li>100.000 Euro turnover</li>
          <li>10.000 Euro advertising expenses</li>
        </ul>
        <p>
          <strong>100.000/ 10.000 = 10</strong>
        </p>
        <p>
          The ROAS is 10:1, so the higher the value achieved, the more profit is
          generated by an ad.
        </p>
        <p>
          <strong>
            There are also individual values for ROAS that are considered
            profitable
          </strong>
          . Basically, it should be above 100%, otherwise the campaign will cost
          more than it brings in.{" "}
          <strong>
            A ratio of 4:1 is set as a benchmark, i.e. achieving four euros in
            profit for one euro invested
          </strong>
          .
        </p>
        <h2>
          <strong>Areas of Application</strong>
        </h2>
        <p>Online advertising and marketing:</p>
        <ul>
          <li>
            Digital advertising campaigns: companies use ROAS and ROI to measure
            and optimize the effectiveness of their online advertising and
            marketing activities.
          </li>
        </ul>
        <p>E-commerce:</p>
        <ul>
          <li>
            Product Sales: E-commerce companies use ROAS and ROI to evaluate the
            success of their online sales strategies and activities, including
            pay-per-click advertising, social media marketing, and email
            marketing.
          </li>
        </ul>
        <p>Investments:</p>
        <ul>
          <li>
            Stocks and Bonds: Investors use ROI to calculate and compare the
            return on their investments in stocks, bonds, and other financial
            instruments.
          </li>
        </ul>
        <p>Real Estate:</p>
        <ul>
          <li>
            Real Estate Investments: Real estate investors use ROI to evaluate
            the profitability of real estate investments, including rental
            properties and real estate development.
          </li>
        </ul>
        <p>Business Planning and Development:</p>
        <ul>
          <li>
            Enterprise Projects: Corporations use ROI to analyze and plan the
            profitability of projects, initiatives, and investments.
          </li>
        </ul>
        <p>Marketing Campaign Evaluation:</p>
        <ul>
          <li>
            Campaign Performance: marketers use ROAS to evaluate the performance
            of individual marketing campaigns or channels such as Google Ads,
            Facebook Ads, and email marketing.
          </li>
        </ul>
        <p>Sales Activities:</p>
        <ul>
          <li>
            Sales Strategies: Companies use ROI to monitor and adjust the
            effectiveness of their sales strategies and efforts.
          </li>
        </ul>
        <p>Product development:</p>
        <ul>
          <li>
            New Product Launches: Companies evaluate ROI to determine the
            success of product development projects and associated investments.
          </li>
        </ul>
        <p>Customer relationship management (CRM):</p>
        <ul>
          <li>
            Customer acquisition and retention: companies use ROAS and ROI to
            measure the value of their customer acquisition and retention
            strategies.
          </li>
        </ul>
        <p>Education and Training:</p>
        <ul>
          <li>
            Continuing Education: Educational institutions and businesses use
            ROI to evaluate the effectiveness of employee training and
            development programs.
          </li>
        </ul>
        <p>Non-profit organizations:</p>
        <ul>
          <li>
            Fundraising: Nonprofits use ROI to analyze the effectiveness of
            their fundraising activities and ensure that donations are being
            used effectively.
          </li>
        </ul>
        <p>Freelancers and self-employed professionals:</p>
        <ul>
          <li>
            Project work: self-employed and freelancers use ROI to determine the
            profitability of their projects and services.
          </li>
        </ul>
        <h2>
          <strong>Limits</strong>
        </h2>
        <p>
          Both ROI and ROAS have their limitations, however, as purchasing
          decisions cannot always be attributed solely to an advertising
          campaign (see also{" "}
          <a href="/en/case-interview-basics/case-cracking-toolbox/practice-your-basics/correlation-and-causality">
            Correlation and Causality
          </a>
          ). In addition, the two values do not reflect the point in the
          customer journey at which the purchase decision was made.&nbsp;
        </p>
        <p>
          In addition, at the beginning of a campaign for a new product, the
          goal may not be to achieve high sales figures immediately, but to
          generate attention or a positive brand image. In this case, the values
          are not meaningful.
        </p>
        <p>
          To obtain a particularly reliable statement, the values should
          therefore be collected regularly and the trend observed.
        </p>
      </article>
      <div class="action-wrapper js-action-wrapper">
        <button
          class="basic-button js-mark-as-read"
          data-uri="/ajax/bootcamp/mark-as-read/110"
        >
          Mark article as read
        </button>
        <button
          class="basic-button basic-button-ghost js-mark-as-unread"
          data-uri="/ajax/bootcamp/mark-as-unread/110"
        >
          Mark article as unread
        </button>
      </div>

      <div class="bootcamp-article-nav bootcamp-article-nav-bottom">
        <div class="bootcamp-article-nav-column prev-column">
          <a
            href="/case-interview-basics/case-cracking-toolbox/practice-your-basics/qualitative-and-quantitative-analysis"
            class="nav-link"
            title="Qualitative and Quantitative Analysis"
          >
            <i class="fas fa-chevron-left nav-icon"></i> Previous article
          </a>
        </div>
        <div class="bootcamp-article-nav-column next-column"></div>
      </div>
    </div>
  );
};

export default RoiAndRoas;
