import React from "react";

const CashFlowStatement = () => {
  return (
    <div class="basic-section article-wrapper js-article-wrapper ">
      <div class="bootcamp-article-nav">
        <div class="bootcamp-article-nav-column prev-column">
          <a
            href="/case-interview-basics/business-concept-library/common-terms-of-business/income-statement"
            class="nav-link"
            title="Income Statement"
          >
            <i class="fas fa-chevron-left nav-icon"></i> Previous article
          </a>
        </div>
        <div class="bootcamp-article-nav-column next-column">
          <a
            href="/case-interview-basics/business-concept-library/common-terms-of-business/supply-and-demand"
            class="nav-link"
            title="Supply and Demand"
          >
            Next article <i class="fas fa-chevron-right nav-icon"></i>
          </a>
        </div>
      </div>
      <article class="basic-article article-content js-article-content">
        <h2>
          <strong>
            The cash flow statement gives an overview of a firm’s ability to
            generate cash
          </strong>
        </h2>
        <p>
          The cash flow statement belongs to one of the three financial
          statements in addition to the&nbsp;
          <a href="/case-interview-basics/business-concept-library/common-terms-of-business/balance-sheet">
            balance sheet
          </a>
          &nbsp;and&nbsp;
          <a href="/case-interview-basics/business-concept-library/common-terms-of-business/income-statement">
            income statement
          </a>
          . Cash flow statements show&nbsp;the inflow/outflow of cash. The key
          difference between a cash flow statement and an income statement is
          that while an item gets listed in the income statement as soon as it
          is accrued, the same item gets listed in the cash-flow statement only
          after the <strong>actual payment has happened</strong>.
        </p>
        <h3>
          <strong>
            Cash flows can be segmented into three major categories:
          </strong>
        </h3>
        <ul>
          <li>
            <strong>Operating cash flows</strong>&nbsp;are a result of the{" "}
            <a href="/case-interview-basics/business-concept-library/useful-business-analysis-tools/core-competencies">
              core business
            </a>{" "}
            in which cash flows are directly generated by manufacturing or
            selling a product. These are necessary to keep the business
            operating.
          </li>
          <li>
            <strong>Investment cash flows</strong>&nbsp;are long-term
            investments into assets such as property or plants.
          </li>
          <li>
            <strong>Financing cash flows</strong>&nbsp;are a result of
            activities such as issuance and repurchase of bonds, equity, and
            dividends.
          </li>
        </ul>
        <h3>
          <strong>
            Cash flow, balance sheet, and financial statement are interdependent
          </strong>
        </h3>
        <p>
          The&nbsp;<strong>income statement</strong>&nbsp;is used to derive the{" "}
          <strong>operating cash flow</strong>:
        </p>
        <ul>
          <li>
            In general, you start with EBIT. All included positions that&nbsp;
            <strong>have no actual influence on cash flows</strong>&nbsp;are
            subtracted. For example: to derive the earnings before interest and
            taxes (EBIT), depreciation is subtracted from the gross profit.
            Since depreciation is not actual cash flow, it has to be added again
            to get a true picture of a firm’s cash flow. &nbsp;Likewise,
            positions that are not included in EBIT, but result in changes in
            cash flow need to be added, e.g. taxes.
          </li>
        </ul>
        <p>
          The&nbsp;<strong>balance sheets</strong>&nbsp;from two consecutive
          years are used to derive the <strong>investment</strong> and{" "}
          <strong>financing</strong> cash flow:
        </p>
        <ul>
          <li>
            Determine the <strong>investment cash flow</strong>&nbsp;over the{" "}
            <strong>asset side</strong> of the balance sheet: If assets increase
            due to investments over the past year, cash-outflows are necessary
            to acquire them. Likewise, if assets such as inventory decrease,
            they result in cash inflows from sales.
          </li>
          <li>
            Use the <strong>financing side</strong> of the balance sheet to
            derive the financing cash flow. If equity or liabilities increase a
            cash inflow must have happened. Of course, you can buy assets
            immediately through debts meaning that the cash from
            getting&nbsp;credit&nbsp;is directly used for the asset.
            Consequently, cash flows possibly cancel each other out.
          </li>
        </ul>
        <p>
          The <strong>sum of all three cash flows</strong>&nbsp;(operating,
          investment and financing) is the final change in cash. You can find
          this change in the balance sheet as the{" "}
          <strong>difference in cash positions</strong> between the current and
          preceding year.
        </p>
        <h3>
          <strong>
            Find below an example of how these three cash flow types can be
            indirectly calculated
          </strong>
        </h3>
        <p>&nbsp;</p>
        <figure class="image">
          <img
            src="/uploads/bootcamp/40/type-conversion-1677685075-3hehkdd2cvgo.webp"
            alt="type-conversion-1677685075-3hehkdd2cvgo.webp"
          />
        </figure>
        <h3>
          <strong>Cash flows are major inputs for company valuations</strong>
        </h3>
        <p>
          <strong>Free cash flow</strong> is another type of cash flow important
          for investors. It depicts the amount of cash that can flow to a{" "}
          <strong>
            company’s security holders in terms of dividends or interests
          </strong>{" "}
          without extracting necessary money for daily operations. Free cash
          flows are often used to determine the{" "}
          <a href="/case-interview-basics/case-cracking-toolbox/identify-your-case-type/valuation">
            company value
          </a>
          &nbsp;by applying{" "}
          <a href="/case-interview-basics/business-concept-library/common-terms-of-business/net-present-value-npv">
            discounting
          </a>{" "}
          principles.
        </p>
        <p>
          Calculations can be done in several different ways. But&nbsp;the key
          idea remains the same: from a company’s income, add everything that
          has been subtracted during profit and loss calculation that has no
          real influence on the level of cash. Subtract everything that is
          needed as an investment to keep the business running at a current
          level. This is usually working capital, or current receivables,
          payables, and capital expenditure &nbsp;(e.g., investments in plants,
          property, and equipment), which have to be renewed.
        </p>
        <p>&nbsp;</p>
        <figure class="image">
          <img
            src="/uploads/bootcamp/40/type-conversion-1677685100-9bpik3ho1bte.webp"
            alt="type-conversion-1677685100-9bpik3ho1bte.webp"
          />
        </figure>
        <h3>
          <strong>Key takeaways</strong>
        </h3>
        <ul>
          <li>
            Cash flows are crucial to&nbsp;<strong>determine liquidity.</strong>
            &nbsp;Positive cash flows are a sign of at least short-term
            solvency.
          </li>
          <li>
            Cash flow emerges from&nbsp;
            <strong>operations, investing, and&nbsp;financing</strong>.
          </li>
          <li>
            Operating cash flows help to assess the company's ability to&nbsp;
            <strong>fund the ongoing business</strong>.
          </li>
          <li>
            Cash flow from&nbsp;investing helps to assess the possibilities
            of&nbsp;<strong>future growth</strong>&nbsp;through investments.
          </li>
        </ul>
      </article>
      <div class="action-wrapper js-action-wrapper">
        <button
          class="basic-button js-mark-as-read"
          data-uri="/ajax/bootcamp/mark-as-read/40"
        >
          Mark article as read
        </button>
        <button
          class="basic-button basic-button-ghost js-mark-as-unread"
          data-uri="/ajax/bootcamp/mark-as-unread/40"
        >
          Mark article as unread
        </button>
      </div>

      <div class="bootcamp-article-nav bootcamp-article-nav-bottom">
        <div class="bootcamp-article-nav-column prev-column">
          <a
            href="/case-interview-basics/business-concept-library/common-terms-of-business/income-statement"
            class="nav-link"
            title="Income Statement"
          >
            <i class="fas fa-chevron-left nav-icon"></i> Previous article
          </a>
        </div>
        <div class="bootcamp-article-nav-column next-column">
          <a
            href="/case-interview-basics/business-concept-library/common-terms-of-business/supply-and-demand"
            class="nav-link"
            title="Supply and Demand"
          >
            Next article <i class="fas fa-chevron-right nav-icon"></i>
          </a>
        </div>
      </div>
    </div>
  );
};

export default CashFlowStatement;
