import React from "react";

const Valuation = () => {
  return (
    <div class="basic-section article-wrapper js-article-wrapper ">
      <div class="bootcamp-article-nav">
        <div class="bootcamp-article-nav-column prev-column">
          <a
            href="/case-interview-basics/case-cracking-toolbox/identify-your-case-type/pricing"
            class="nav-link"
            title="Pricing"
          >
            <i class="fas fa-chevron-left nav-icon"></i> Previous article
          </a>
        </div>
        <div class="bootcamp-article-nav-column next-column">
          <a
            href="/case-interview-basics/case-cracking-toolbox/identify-your-case-type/brainteaser"
            class="nav-link"
            title="Brainteaser"
          >
            Next article <i class="fas fa-chevron-right nav-icon"></i>
          </a>
        </div>
      </div>
      <article class="basic-article article-content js-article-content">
        <h2>
          <strong>
            Valuation Cases Usually Require Estimating the Price of a Firm,
            Patent, or Service in the Market&nbsp;
          </strong>
        </h2>
        <p>
          This type of case can either be a subset of an&nbsp;
          <a href="/en/case-interview-basics/case-cracking-toolbox/identify-your-case-type/ma">
            M&amp;A
          </a>
          &nbsp;case, in which you need to know a company's worth before
          purchasing, or a standalone case (rare). For instance, “How much is
          Pfizer worth today?” In strategy consulting, these questions are
          rather rarely seen. However, cases where you do need to valuate
          something usually start with “<i>How much would you pay for…</i>”
        </p>
        <h3>
          The most common methods of valuating are the Discounted Cash Flow
          (DCF) and the industry multiple method
        </h3>
        <p>
          As these are still case studies meant to fit in an interview round,
          the interviewer will very likely not ask you to perform an exact and
          comprehensive valuation analysis. Instead, you may be required to
          estimate the worth of a product, patent, or a service. You may also
          have to judge if an offered price is reasonable.
        </p>
        <h3>
          <strong>Discounted Cash Flow method</strong>
        </h3>
        <p>
          The first valuation method is the Discounted Cash Flow method. This
          method shows how much money you would have in your savings account at
          a certain interest rate in order to provide you with the same annual
          cash flow generated by the company that is being evaluated. Here, you
          simply divide projected annual cash flows by a discounted rate (or
          interest rate). Of course, the discount rate of your savings account
          will be much lower than that of an investment in a company. This is so
          because the risk you take putting your money in a savings account is
          much lower than the risk of investing in a company.
        </p>
        <p></p>
        <div class="highlight-box highlight-box-light-grey js-highlight-box">
          For more details on how to use the Discounted Cash Flow (DCF) method,
          have a look at our{" "}
          <a href="/en/case-interview-basics/business-concept-library/common-terms-of-business/net-present-value-npv">
            Net Present Value (NPV)
          </a>
          &nbsp;lesson
        </div>
        <h3>
          <strong>Industry multiple method</strong>
        </h3>
        <p>
          The DCF method is limited since&nbsp;it does not take into account
          additional dimensions other than money (unless you quantify those
          dimensions into the future cash flows).
        </p>
        <p>
          Football teams, for instance, are often overvalued compared to their
          generated returns. For such cases, there is another method called the
          industry multiple method.
        </p>
        <p>
          This method allows you to valuate a firm by using a metric known to
          this company and multiplying it by the associated industry multiple.
          This can be done for&nbsp;similar players in the industry to assess
          their relative valuations using&nbsp;
          <a href="/en/case-interview-basics/business-concept-library/useful-business-analysis-tools/benchmarking">
            benchmarking
          </a>
          .
        </p>
        <p>
          An example of a multiple ratio is the price-to-book ratio (P/B). This
          multiple is the ratio of the&nbsp;
          <strong>actual firm valuation</strong>&nbsp;(based for example on{" "}
          <a href="/en/case-interview-basics/case-cracking-toolbox/identify-your-case-type/ma">
            M&amp;A
          </a>
          &nbsp;deals) and the&nbsp;
          <strong>book&nbsp;value of the same firm&nbsp;</strong>(value of its
          assets, which can be found in the{" "}
          <a href="/en/case-interview-basics/business-concept-library/common-terms-of-business/balance-sheet">
            balance sheet
          </a>
          ).&nbsp;If a firm’s assets added up to 200 million, and it was sold
          for 100 million, the ratio is 0.5 (100 million/200 million). Do this
          for a set of representative industry players, take the average and you
          get the average industry multiple. Finally, you multiply the industry
          multiple with the value of the assets.&nbsp;
        </p>
        <p>
          Other commonly used ratios are the price-earnings ratio (P/E ratio or
          PER) and the EBITDA ratio.
        </p>
        <p>
          Since you will not be required to calculate the value of an investment
          on too high a level of detail, it is not necessary to learn values for
          different interest rates or industry multiples by heart. However, to
          give you an idea about orders of magnitude:
        </p>
        <ul>
          <li>A good guess for an industry multiple is EBITDA*10.</li>
          <li>
            Good guesses for interest rates would range from 3% (inflation) to
            up to 20% for highly speculative investments.
          </li>
        </ul>
        <h2>Key takeaways</h2>
        <ul>
          <li>
            Use the&nbsp;<strong>Discounted Cash Flow (DCF)</strong> method to
            valuate a firm based solely on its expected profits.
          </li>
          <li>
            Use the <strong>industry multiple method</strong> to double-check if
            the DCF valuation is reasonable. Sometimes other aspects need to be
            factored in like brand value, customer loyalty, liabilities, etc.
          </li>
          <li>
            There are several types of industry multiples to choose from. For
            more precise valuation, choose more types of industry multiples.
          </li>
        </ul>
      </article>
      <div class="action-wrapper js-action-wrapper">
        <button
          class="basic-button js-mark-as-read"
          data-uri="/en/ajax/bootcamp/mark-as-read/51"
        >
          Mark article as read
        </button>
        <button
          class="basic-button basic-button-ghost js-mark-as-unread"
          data-uri="/en/ajax/bootcamp/mark-as-unread/51"
        >
          Mark article as unread
        </button>
      </div>

      <div class="bootcamp-article-nav bootcamp-article-nav-bottom">
        <div class="bootcamp-article-nav-column prev-column">
          <a
            href="/en/case-interview-basics/case-cracking-toolbox/identify-your-case-type/pricing"
            class="nav-link"
            title="Pricing"
          >
            <i class="fas fa-chevron-left nav-icon"></i> Previous article
          </a>
        </div>
        <div class="bootcamp-article-nav-column next-column">
          <a
            href="/en/case-interview-basics/case-cracking-toolbox/identify-your-case-type/brainteaser"
            class="nav-link"
            title="Brainteaser"
          >
            Next article <i class="fas fa-chevron-right nav-icon"></i>
          </a>
        </div>
      </div>
    </div>
  );
};

export default Valuation;
